{'author': 'Advitus',
 'category': 'Website',
 'currency': 'EUR',
 'data': ['security/ir.model.access.csv',
          'views/assets.xml',
          'views/snippets.xml',
          'views/website_product_slider.xml',
          'views/templates.xml'],
 'demo': [],
 'depends': ['website_sale'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'https://demo.minilini.com/page/start/website_sale_product_slider/14.0',
 'name': 'Product Slider Building Block',
 'price': 30.0,
 'qweb': [],
 'summary': 'Building Block that allows you to create product sliders from '
            'picked products',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '14.0.1.0.0',
 'website': 'https://demo.minilini.com'}

